echo Copying missing files
pause.
copy /y /b .\1394bus.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\85f1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\85f1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\85f874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\85s1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\85s1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\85s874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\a15.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\a234.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\acc_dis.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\access.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\access.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\accessib.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\acerscan.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\achg.asp	X:\ISOs\missing\amd64missing\
copy /y /b .\aclui.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\aclui.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\acode.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\actconn.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\actdone.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\activ.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\activerr.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\activsvc.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\actlan.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\actshell.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\adcjavas.inc	X:\ISOs\missing\amd64missing\
copy /y /b .\adcvbs.inc	X:\ISOs\missing\amd64missing\
copy /y /b .\addremov.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ade.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\adeskerr.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\admtoolw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\adojavas.inc	X:\ISOs\missing\amd64missing\
copy /y /b .\adovbs.inc	X:\ISOs\missing\amd64missing\
copy /y /b .\adprop.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\adpu160m.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\adpu320.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\adrdyreg.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\aelupsvc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\aexp2b.asp	X:\ISOs\missing\amd64missing\
copy /y /b .\aexp4b.asp	X:\ISOs\missing\amd64missing\
copy /y /b .\afd.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\agentanm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentctl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentdp2.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentdpv.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentmpx.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentpsh.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentsr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agentsvr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\agp.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\agrmco64.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0401.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0401.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0404.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0404.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0405.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0405.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0406.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0406.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0407.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0407.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0408.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0408.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0409.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0409.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040b.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040b.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040c.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040c.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040d.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040d.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040e.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt040e.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0410.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0410.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0411.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0411.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0412.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0412.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0413.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0413.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0414.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0414.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0415.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0415.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0416.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0416.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0419.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0419.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt041d.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt041d.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt041f.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt041f.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0804.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0804.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0816.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0816.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0c0a.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\agt0c0a.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\agtctl15.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\agtinst.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\agtintl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ahronbd.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\aic78u2.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\aic78xx.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\aliide.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\amdide.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\amipro.sam	X:\ISOs\missing\amd64missing\
copy /y /b .\andlso.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsa.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsab.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsai.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsau.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsaub.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsaui.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsauz.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\angsaz.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\apolicy.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\app932.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\app936.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\app949.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\app950.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\apps_sp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\aprvcyms.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\arc.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\areg1.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\aregdial.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\aregdone.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\aregsty2.css	X:\ISOs\missing\amd64missing\
copy /y /b .\aregstyl.css	X:\ISOs\missing\amd64missing\
copy /y /b .\arp.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\arphr.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\arptr.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\array30.tab	X:\ISOs\missing\amd64missing\
copy /y /b .\arrayhw.tab	X:\ISOs\missing\amd64missing\
copy /y /b .\article.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\artrbdo.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\artro.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\asp.mfl	X:\ISOs\missing\amd64missing\
copy /y /b .\asr_ldm.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\asycfilt.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\atiixpag.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\atixpwdm.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\atl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\atm.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\atmadm.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\atmfd.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\atmlib.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\atmuni.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\att.ht	X:\ISOs\missing\amd64missing\
copy /y /b .\audiocdc.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\auditusr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\auditw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ausrinfo.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\avmamd64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\avmunet.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\balloon.xsl	X:\ISOs\missing\amd64missing\
copy /y /b .\bar.xsl	X:\ISOs\missing\amd64missing\
copy /y /b .\batang.ttc	X:\ISOs\missing\amd64missing\
copy /y /b .\bitsprx3.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\blurbs.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\blutooth.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\bootconp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\brief.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\brmfcmdm.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\brmfcmf.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\brmfcsto.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\brmfcumd.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\brmfcwia.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\brmfport.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\brmsi02f.icm	X:\ISOs\missing\amd64missing\
copy /y /b .\brmsi03.icm	X:\ISOs\missing\amd64missing\
copy /y /b .\brmsi03f.icm	X:\ISOs\missing\amd64missing\
copy /y /b .\browa.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browab.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browai.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browau.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browaub.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browaui.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browauz.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\browaz.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\bth.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\bthpan.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\bthprint.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\bthspp.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\btpanui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\c8514fix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\c8514oem.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\c8514sys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\cabinet.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\calc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\calc.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\camera.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\camera.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\catsrv.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\catsrvps.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\catsrvut.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\cdac15ba.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\cdac15ba.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\cdad10ba.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\cdad10ba.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\cdmedia.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cdmedia.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\cdosys.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\certmgr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\certmgrw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\chajei.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\charchsr.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\charctxt.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\charmap.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\charmap.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\chnscsvr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\chooser.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\chsbrkr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\chtapt.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\chtapt.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\chtapten.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\chtbrkr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\chtpaden.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\chtskdic.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\chtskdic.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\chtskf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\cintime.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgb.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgd.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgie.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgl.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgnt.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgnt.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgnt.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgnt.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgs.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgsi.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlgu.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintlguc.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\cintsetp.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\cis.ht	X:\ISOs\missing\amd64missing\
copy /y /b .\cjhlpen.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cjhlpen.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\cjhlpen.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\clbcatex.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\clbcatq.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\cliconf.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cliconfg.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\cliconfg.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\cliconfg.rll	X:\ISOs\missing\amd64missing\
copy /y /b .\clipbrd.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\clipbrd.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\cmconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cmdide.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\cmmgr32.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\cmsetacl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\cnncterr.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\colbact.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\colormgt.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\comaddin.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comadmin.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comempty.dat	X:\ISOs\missing\amd64missing\
copy /y /b .\comexp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\comexp.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\comexp.msc	X:\ISOs\missing\amd64missing\
copy /y /b .\common.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\comntwks.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\compfldr.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\compmgtw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\compstui.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\comrepl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comrepl.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\comrereg.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\comres.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comsetup.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comsnap.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comsvcs.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\comuid.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\conf1.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cordia.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiab.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiai.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiau.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiaub.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiaui.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiauz.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\cordiaz.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\corpol.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\coue1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\coue1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\couf1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\couf1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\courtney.acs	X:\ISOs\missing\amd64missing\
copy /y /b .\cpan_w64.chq	X:\ISOs\missing\amd64missing\
copy /y /b .\cpanelw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\cplexe.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\cscript.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\cscui.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\cvgafix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\cvgasys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\d3d9.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\d3dxof.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dataspec.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\datetime.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\david.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\davidbd.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\davidtr.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\dayi.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\dayiphr.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\dayiptr.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\dbnetlib.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dbnmpntw.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dcomcnfg.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\ddraw.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\defrag.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\defrag.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\defragp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\devmgr.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\devmgr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrg.msc	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgfat.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgifc.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgifps.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgntfs.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgres.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgsnap.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dfrgui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dfs.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\diagbtp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\dialer.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\dialer.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\dialmgr.js	X:\ISOs\missing\amd64missing\
copy /y /b .\dialtone.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\dialtone.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\dialup.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\dialup.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\diantz.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dijoy.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\dimsntfy.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dimsroam.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\diskmgmt.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\diskmgtw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\diskpart.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dispex.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\display.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\displayw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\divsx64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\dkconp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\dmadmin.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dmboot.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\dmconfig.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmdlgs.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmdskmgr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmdskres.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmintf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmio.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\dmivcitf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmload.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\dmremote.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dmserver.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmusic.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\dmvdsitf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dmview.ocx	X:\ISOs\missing\amd64missing\
copy /y /b .\dpcdll.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dpti2o.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\dpvacm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dpvoice.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dpvsetup.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dpvvox.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\drm.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\drwtsn32.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\drwtsn32.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\ds32gt.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dsclient.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\dsdmo.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dskquop.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\dskquoui.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\dssenh.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dtcntwks.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\dwil1033.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dwwin.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\dxdiagn.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\dxtrans.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\earl.acs	X:\ISOs\missing\amd64missing\
copy /y /b .\els.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\els.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\encapi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\encryptw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\error.js	X:\ISOs\missing\amd64missing\
copy /y /b .\error.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\es.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\estre.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\eudcedit.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\eudcedit.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\eula.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\evcon.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\evntwin.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\excel.xls	X:\ISOs\missing\amd64missing\
copy /y /b .\excel4.xls	X:\ISOs\missing\amd64missing\
copy /y /b .\extmgr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\extrac32.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\fde.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\file_srv.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\filefldw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\filefold.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\filelist.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\filemgmt.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\findw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\finger.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\finish.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\firewall.cpl	X:\ISOs\missing\amd64missing\
copy /y /b .\flash.ocx	X:\ISOs\missing\amd64missing\
copy /y /b .\fltlib.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\fltmc.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\fltmgr.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\fltmgr.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\folderop.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\font.dat	X:\ISOs\missing\amd64missing\
copy /y /b .\fonts.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\fonts.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\fontsub.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\frank.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\freecell.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\freecell.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\ftp.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\fwcfg.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\gameport.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\gautami.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\genw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\glosw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\gpedit.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\gpeditw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\gptext.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\guitrn.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\gulim.ttc	X:\ISOs\missing\amd64missing\
copy /y /b .\h323msp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\h8514fix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\h8514oem.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\h8514sys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\halftone.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\handler.reg	X:\ISOs\missing\amd64missing\
copy /y /b .\handler.srg	X:\ISOs\missing\amd64missing\
copy /y /b .\handsafe.reg	X:\ISOs\missing\amd64missing\
copy /y /b .\hanja.lex	X:\ISOs\missing\amd64missing\
copy /y /b .\hanjadic.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hardware.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\hardware.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\hbaapi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hdaudbus.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\hdaudio.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\hh.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\hhctrl.ocx	X:\ISOs\missing\amd64missing\
copy /y /b .\hhctrlui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hhsetup.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hidbth.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\hilgbbs.ht	X:\ISOs\missing\amd64missing\
copy /y /b .\hlink.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hndshake.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\hnetwiz.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hostname.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\howtow.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\hpc4500u.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpcclj.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpclj5.ini	X:\ISOs\missing\amd64missing\
copy /y /b .\hpclj5ui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt21.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt21tk.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt33.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt33tk.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt34.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt34tk.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt42.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt42tk.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgt53.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hpgtmcro.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hplj5si.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\hpoj780.gpd	X:\ISOs\missing\amd64missing\
copy /y /b .\hpoj780i.gpd	X:\ISOs\missing\amd64missing\
copy /y /b .\hpojv60.gpd	X:\ISOs\missing\amd64missing\
copy /y /b .\hpojv60i.gpd	X:\ISOs\missing\amd64missing\
copy /y /b .\hs.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\hschelpw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\hscupd.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\html.iec	X:\ISOs\missing\amd64missing\
copy /y /b .\hvgafix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\hvgasys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\hwdb.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\hypertrm.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\hypertrm.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\i2omgmt.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\i2omp.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\ialmnt5.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\iconlib.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\icsmgr.js	X:\ISOs\missing\amd64missing\
copy /y /b .\ident.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\ieakmmc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ieencode.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ieeula.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ieos.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ieshared.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\iesupp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\iewebhlp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\iexplore.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\iexplore.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\igames.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\iirsp.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\iisadmin.mfl	X:\ISOs\missing\amd64missing\
copy /y /b .\iisadmin.mof	X:\ISOs\missing\amd64missing\
copy /y /b .\iisntw64.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\iispwchg.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\iiswmmc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imapi.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imekr.lex	X:\ISOs\missing\amd64missing\
copy /y /b .\imekr61.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\imekrcic.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imekrmig.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imepaden.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imepadsm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imepadsv.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imeshare.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imgprev.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjp81.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\imjp81k.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcd.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpch.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcic.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcl.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcl.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcle.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcle.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpcus.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpdadm.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpdct.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpdct.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpdsvr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpdt.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpdte.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpgn.grm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpinst.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpinst.ini	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpln.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpmig.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpnm.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjppd.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjprw.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpsb.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpsm.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpsm.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpsme.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpsme.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpst.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjptk.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imjptu.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpuex.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjputy.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imjputyc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imjpzp.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\imkr61.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imkr61.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imkren61.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imkren61.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\imkrinst.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imkrinst.ini	X:\ISOs\missing\amd64missing\
copy /y /b .\imlang.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\impdko61.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\imscinst.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\imskdic.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\imskf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\indxsvc.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\inetfind.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\inetopts.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\inetpref.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\inetres.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\inetsrch.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\infosoft.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\infrared.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\infrared.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\input.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\input.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\instcat.sql	X:\ISOs\missing\amd64missing\
copy /y /b .\intellim.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\intents.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\intro.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\ip6fw.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\ippromon.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ipseconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ipsecsnp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ipsecsnp.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\ipsecsvc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ipsecw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ipv6p.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\irbus.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\isconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\isp2busy.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\isw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\itircl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\itss.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ixhelp.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\j8514fix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\j8514oem.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\j8514sys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\joy.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\jpnpaden.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\jscript.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\jsmalle.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\jsmallf.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\jvgafix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\jvgasys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\key.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\keyb.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\keyshort.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\kodak_dc.icm	X:\ISOs\missing\amd64missing\
copy /y /b .\korpaden.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\korwbrkr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\korwbrkr.lex	X:\ISOs\missing\amd64missing\
copy /y /b .\lang.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\langbar.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\latha.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\lcladv.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcladvd.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcladvdf.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcladvmm.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclcomp.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcldate.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcldocs.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclkwrds.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcllook.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclmm.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclmode.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclother.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclprog.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclrfine.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclsize.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lclsrch.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcltechy.xml	X:\ISOs\missing\amd64missing\
copy /y /b .\lcphrase.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\lcptr.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\licdll.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\license.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\licwmi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\licwmi.mfl	X:\ISOs\missing\amd64missing\
copy /y /b .\licwmi.mof	X:\ISOs\missing\amd64missing\
copy /y /b .\localsec.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\locsecw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\log.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\lotus.wk4	X:\ISOs\missing\amd64missing\
copy /y /b .\lpe.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\lpecon.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\lpq.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\lpr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\lprhelp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\lprmon.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\lprmonui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\lvnm.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\lvnmbd.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mag_hook.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\magnify.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\magnify.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\magnify.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\mail.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\makecab.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\mangal.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mci.ht	X:\ISOs\missing\amd64missing\
copy /y /b .\mciqtz32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mdacrdme.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\mdmagm64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\mdmags64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\mdmbtmdm.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\mdmcnxt4.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\mdmusrgl.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\merlin.acs	X:\ISOs\missing\amd64missing\
copy /y /b .\mfc42.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mfc42u.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mfcsubs.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mfcuix.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\migapp.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\migdial.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\migip.dun	X:\ISOs\missing\amd64missing\
copy /y /b .\migism.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\migism.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\migload.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\migrate.isp	X:\ISOs\missing\amd64missing\
copy /y /b .\migrate.obe	X:\ISOs\missing\amd64missing\
copy /y /b .\migregdb.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\migsys.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\miguser.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\migwiz.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\migwiz.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\migwiz.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\migwiz.man	X:\ISOs\missing\amd64missing\
copy /y /b .\migwiz2.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\migx25a.dun	X:\ISOs\missing\amd64missing\
copy /y /b .\migx25b.dun	X:\ISOs\missing\amd64missing\
copy /y /b .\migx25c.dun	X:\ISOs\missing\amd64missing\
copy /y /b .\mingliu.ttc	X:\ISOs\missing\amd64missing\
copy /y /b .\miniime.tpl	X:\ISOs\missing\amd64missing\
copy /y /b .\miscw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mll_hp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mll_mtf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mll_qic.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mls_trb.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mmc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mmc_dlg.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\mnmdd64.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mobsync.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mobsync.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\modem.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\modew.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mouse.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mouse.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\moviemk.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\mpconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mpg2data.ax	X:\ISOs\missing\amd64missing\
copy /y /b .\mpg2splt.ax	X:\ISOs\missing\amd64missing\
copy /y /b .\mplayer2.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\mpnetwrk.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\mprddm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mqlogmgr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mriam.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mriamc.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mriamfx.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mriamtr.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mrinfo.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\msadce.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadcer.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadcf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadcfr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadco.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadcor.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadcs.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadds.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msaddsr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msader15.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msado15.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msado20.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\msado21.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\msado25.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\msado26.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\msado27.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\msadomd.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msador15.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadox.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msadrh15.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msafd.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msbbs.ht	X:\ISOs\missing\amd64missing\
copy /y /b .\msconfig.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\msdadiag.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdaosp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdaprsr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdaprst.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdaps.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdarem.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdaremr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdart.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdasc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\msdatl3.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdatsrc.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\msdayi.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\msdfmap.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdfmap.ini	X:\ISOs\missing\amd64missing\
copy /y /b .\msdlg874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtc.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtclog.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtcprf.h	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtcprf.ini	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtcprx.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtcstp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtctm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtctr.mof	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtcuiu.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msdtcvtr.bat	X:\ISOs\missing\amd64missing\
copy /y /b .\msgothic.ttc	X:\ISOs\missing\amd64missing\
copy /y /b .\msgr3en.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msgrocm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msgsc64.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mshearts.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mshearts.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\mshearts.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\msinfo32.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\msir3jp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msir3jp.lex	X:\ISOs\missing\amd64missing\
copy /y /b .\mslwvtts.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msmincho.ttc	X:\ISOs\missing\amd64missing\
copy /y /b .\msmsgs.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\msmusb.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\msnmsn.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\msobcomm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msobdl.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msobe.isp	X:\ISOs\missing\amd64missing\
copy /y /b .\msobmain.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msobshel.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msobweb.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msoobe.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\mspaint.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mspaint.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\mspmsnsv.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mstask.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\mstaskw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\mstsc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\msvcp60.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mswrd6.wpc	X:\ISOs\missing\amd64missing\
copy /y /b .\mswrd8.wpc	X:\ISOs\missing\amd64missing\
copy /y /b .\mswsock.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msxactps.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msxml3.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msxml3r.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\msxs64.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mtsadmin.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\mtstocom.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\mtxclu.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mtxdm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mtxex.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mtxoci.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\multibox.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\mvboli.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\mymusic.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\ncxpnt.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ndisnpp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\net57amd.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\net8169a.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netamd81.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netanax.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netbc564.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netcfg.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\netcfgw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\netclass.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\nete1g3e.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netefe3e.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netfea64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netfw.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netgea64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netixg3e.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netloop.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netmrvl.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netnm.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netnvid6.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netnwlnk.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netrndis.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netrtsnx.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netsap.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netsetup.cpl	X:\ISOs\missing\amd64missing\
copy /y /b .\netsisx.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netuli64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\netw64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\networkw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\netxea64.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat1.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat1.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat2.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat2.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat3.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat3.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat4.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat4.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat5.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\newfeat5.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\nls302en.lex	X:\ISOs\missing\amd64missing\
copy /y /b .\nmnt.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\nntpsnap.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\nntpsnap.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\nntpsnap.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\noanswer.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\nocontnt.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\nofts.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.deu	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.eng	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.enu	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.esn	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.fra	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.ita	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.jpn	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.kor	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.nld	X:\ISOs\missing\amd64missing\
copy /y /b .\noise.sve	X:\ISOs\missing\amd64missing\
copy /y /b .\notepad.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\notepad.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\nppagent.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\npptools.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\nrkis.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\nslookup.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\nt5iis.cat	X:\ISOs\missing\amd64missing\
copy /y /b .\ntartw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ntbackup.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\ntbackup.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\ntbckupw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ntchowto.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ntcmdsw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ntdef64.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\nthelp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmsapi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmsdba.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmsevt.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmsmgr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmsmgr.msc	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmsoprq.msc	X:\ISOs\missing\amd64missing\
copy /y /b .\ntmssvc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ntshared.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ntshrui.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\nusrmgrw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\nv4_disp.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\nwdoc.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\nwdocw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\nwprovau.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\oakley.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obeip.dun	X:\ISOs\missing\amd64missing\
copy /y /b .\objsel.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0404.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0407.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb040c.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0410.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0411.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0412.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb041d.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0804.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\obrb0c0a.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ocmsn.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbc32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbc32gt.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcad32.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcbcp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcconf.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcconf.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcconf.rsp	X:\ISOs\missing\amd64missing\
copy /y /b .\odbccp32.cpl	X:\ISOs\missing\amd64missing\
copy /y /b .\odbccp32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbccr32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbccu32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcinst.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\odbcint.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\odbctrac.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\oembios.bin	X:\ISOs\missing\amd64missing\
copy /y /b .\oembios.cat	X:\ISOs\missing\amd64missing\
copy /y /b .\oembios.dat	X:\ISOs\missing\amd64missing\
copy /y /b .\oembios.sig	X:\ISOs\missing\amd64missing\
copy /y /b .\oemcoa.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\offlfdrw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ohci1394.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\oleaut32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\oledb32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\oledb32r.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\oledbjvs.inc	X:\ISOs\missing\amd64missing\
copy /y /b .\oledbvbs.inc	X:\ISOs\missing\amd64missing\
copy /y /b .\omc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\oobebaln.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\oobeinfo.ini	X:\ISOs\missing\amd64missing\
copy /y /b .\oobestyl.css	X:\ISOs\missing\amd64missing\
copy /y /b .\oobeutil.js	X:\ISOs\missing\amd64missing\
copy /y /b .\osk.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\osk.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\p2p.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\packager.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\padrs404.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\padrs411.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\padrs412.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\padrs804.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\passwrdw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pberr.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\phhlp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\phhlp.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\phhlp.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\phhlpen.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\phhlpen.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\phhlpen.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\philcam2.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\phon.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\phon.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\phoncode.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\phone.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\phone.obe	X:\ISOs\missing\amd64missing\
copy /y /b .\phonptr.tbl	X:\ISOs\missing\amd64missing\
copy /y /b .\phowto.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\phvfwext.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\pinball.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pinball.dat	X:\ISOs\missing\amd64missing\
copy /y /b .\pinball.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\pinball.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\pinball.mid	X:\ISOs\missing\amd64missing\
copy /y /b .\pinball2.mid	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlcsa.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlcsd.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlcsd.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlcsk.dic	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgc.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgd.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgdx.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgi.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgix.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgl.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgne.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgnt.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgnt.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgr.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlgs.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlpad.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlpad.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlpae.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlpae.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\pintlphr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\pmigrate.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\powerpnt.ppt	X:\ISOs\missing\amd64missing\
copy /y /b .\presenta.shw	X:\ISOs\missing\amd64missing\
copy /y /b .\printfnd.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\printw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_intr.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_intr.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_nav.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_nav.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg1.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg1.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg2.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg2.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg3.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg3.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg4.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg4.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg5.swf	X:\ISOs\missing\amd64missing\
copy /y /b .\pro_seg5.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\prodkey.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\progman.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\progman.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\progress.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\prvcyms.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\psnppagn.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ptilink.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\pulse.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\pwrmn.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\pwrmnw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\qcap.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\qdv.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\qdvd.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\qosconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\qosname.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\quartz.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\quattro.wb2	X:\ISOs\missing\amd64missing\
copy /y /b .\quick.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\r2brand.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\raavi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\rasppp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ratings.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ratings.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\ratings.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\rcnterr.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\rcp.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rdsktpw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rdtone.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\reader.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\reader.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\recycle.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\refdial.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\reg.isp	X:\ISOs\missing\amd64missing\
copy /y /b .\regdial.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\regedit.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\regedit.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\regopt.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\remasst.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\reskitw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rexec.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rhndshk.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\rktools.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rmcast.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\rnoansw.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\rnomdm.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\rnr20.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\rod.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\rodtr.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\romanime.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\route.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rover.acs	X:\ISOs\missing\amd64missing\
copy /y /b .\rpberr.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\rpulse.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\rrcw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rsaci.rat	X:\ISOs\missing\amd64missing\
copy /y /b .\rsaenh.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\rsh.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rsm.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rsm.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\rsmconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rsmmllsv.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rsmps.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\rsmsink.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rsmui.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rsmw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rsopsnpw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rsopw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\rstrui.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\rtoobusy.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\s8514fix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\s8514oem.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\s8514sys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\saferw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\safrconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sapicpl.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\scarddlg.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sccbase.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sccsccp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sceconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\scew.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\scm.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\scmcon.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\script.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\scripto.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\scrobj.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\scrrun.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\scw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sdbus.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\secauth.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\secdrv.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\secdrv.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\secedit.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\secsconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\secsetw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\secupd.dat	X:\ISOs\missing\amd64missing\
copy /y /b .\secupd.sig	X:\ISOs\missing\amd64missing\
copy /y /b .\sendcmsg.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sendcmsg.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sere1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\sere1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\serf1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\serf1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\setupacc.txt	X:\ISOs\missing\amd64missing\
copy /y /b .\sffdisk.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\sfmmgr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\shell.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\shruti.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\sigverif.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\simhei.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\simpbdo.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\simpdata.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\simpfxo.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\simpo.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\simsun.ttc	X:\ISOs\missing\amd64missing\
copy /y /b .\skins.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\sma0w.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\smae1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\smae1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\smaf1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\smaf1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\smbinst.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\smlgcfgw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\smtpsnap.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\smtpsnap.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\smtpsnap.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sndvol32.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sndvol32.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\snmpcon.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\snmpsnap.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\softkey.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sol.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sol.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sound1.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound104.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound105.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound108.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound111.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound112.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound12.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound13.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound131.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound136.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound14.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound16.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound17.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound18.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound181.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound19.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound20.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound21.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound22.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound24.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound240.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound243.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound25.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound26.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound27.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound28.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound29.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound3.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound30.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound34.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound35.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound36.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound38.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound39.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound4.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound42.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound43.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound45.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound49.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound49d.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound5.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound50.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound528.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound53.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound54.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound55.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound560.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound563.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound57.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound58.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound6.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound65.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound68.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound7.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound713.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound735.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound8.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound827.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound9.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\sound999.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\soundrec.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\soundrec.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sounds.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\spad.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sparrow.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\spconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\speech.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\spider.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\spider.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\spider.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\splash.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\spolconw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0404.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0407.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra040c.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0410.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0411.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0412.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra041d.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0804.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\spra0c0a.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0404.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0407.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb040c.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0410.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0411.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0412.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb041d.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0804.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sprb0c0a.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sqloledb.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sqloledb.rll	X:\ISOs\missing\amd64missing\
copy /y /b .\sqlsodbc.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sqlsrv32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sqlsrv32.rll	X:\ISOs\missing\amd64missing\
copy /y /b .\sqlxmlx.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sqlxmlx.rll	X:\ISOs\missing\amd64missing\
copy /y /b .\sr.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\sr.mof	X:\ISOs\missing\amd64missing\
copy /y /b .\sr.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\sr_uiw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\srchctls.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\srchui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\srclient.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\srdiag.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\srframe.mmf	X:\ISOs\missing\amd64missing\
copy /y /b .\srrstr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\srsvc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\srv_info.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\ssdpapi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ssdpsrv.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ssee1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\ssee1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\ssee874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\ssef1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\ssef1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\ssef874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\stclient.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\stdole2.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\stdole32.tlb	X:\ISOs\missing\amd64missing\
copy /y /b .\supp_ed.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\suptools.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\svgafix.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\svgasys.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\swpaback.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\swpabtm.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\swpaflag.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\swpakey.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\swpatop.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\sym_hi.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\sym_u3.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\symc810.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\symc8xx.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\symmpi.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\sys_srv.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sysdm.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sysdmw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sysfiles.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\sysmod.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\sysmon.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sysmonw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sysprop.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\sysrestr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\sysrestw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\syssetup.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\system.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\t2embed.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\table.bmp	X:\ISOs\missing\amd64missing\
copy /y /b .\tapi.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\tapip.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\taskbarw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\taskmgr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\taskmgrw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\tcpipw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\tdibth.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\telnet.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\telnetw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\tftp.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\timesrv.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\tintlgc.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\tintlgl.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\tintlgnt.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\tintlgs.imd	X:\ISOs\missing\amd64missing\
copy /y /b .\tintlphr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\tintsetp.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\tlsbln.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\toobusy.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\toside.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\tourw.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\tradbdo.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\trado.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\tsd32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\tshoot.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\tssoft32.acm	X:\ISOs\missing\amd64missing\
copy /y /b .\tunga.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\twain.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\twclient.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\twclient.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\twunk_16.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\txflog.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\u126v039.bin	X:\ISOs\missing\amd64missing\
copy /y /b .\uagp35.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\udhisapi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ultra.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\unicdime.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\uniime.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\upcdb.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcdbi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcdi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcdl.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upceb.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcebi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcei.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcel.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcfb.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcfbi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcfi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcfl.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcib.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcibi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcii.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcil.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcjb.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcjbi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcji.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcjl.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upckb.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upckbi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcki.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upckl.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upclb.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upclbi.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcli.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\upcll.ttf	X:\ISOs\missing\amd64missing\
copy /y /b .\updat164.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\update.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\update.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\updtblk.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\upnp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\upnpcont.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\upnphost.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\upnpui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\usbccid.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\usbvideo.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\usercpl.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\users.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\usmtdef.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\usp10.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\utilmgr.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\utilmgr.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\uwdf.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\vbscript.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\vds.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\vds_ps.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\vdsbas.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\vdsdyndr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\vdsldr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\vdsutil.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\verifier.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\vga932.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vga936.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vga949.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vga950.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgaf1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgaf1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgaf874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgas1255.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgas1256.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgas874.fon	X:\ISOs\missing\amd64missing\
copy /y /b .\vgx.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\viaide.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\voiceeng.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\voicejp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\voicepad.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\voicesub.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\w03a2409.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\w3core.mfl	X:\ISOs\missing\amd64missing\
copy /y /b .\w3dt.mfl	X:\ISOs\missing\amd64missing\
copy /y /b .\w3dt.mof	X:\ISOs\missing\amd64missing\
copy /y /b .\w3isapi.mfl	X:\ISOs\missing\amd64missing\
copy /y /b .\wavemix.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.deu	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.enu	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.esn	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.fra	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.ita	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.nld	X:\ISOs\missing\amd64missing\
copy /y /b .\wbdbase.sve	X:\ISOs\missing\amd64missing\
copy /y /b .\wbemtest.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wdfmgr.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\wdma_amd.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\webpub.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\whatneww.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wiadss.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wiawow64.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\win_dos.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winar30.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\winchat.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winchat.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\wind64.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wind_w64.chq	X:\ISOs\missing\amd64missing\
copy /y /b .\windows.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\windows.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\wingb.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wingb.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\winhelp.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\winhlp32.cnt	X:\ISOs\missing\amd64missing\
copy /y /b .\winhlp32.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\winime.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winime.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\wininstp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winmine.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winmine.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\winnt32.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\winnt32.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\winnt32u.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\winpy.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winpy.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\winpy.mb	X:\ISOs\missing\amd64missing\
copy /y /b .\winshfhc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\winsp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winsp.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\winsp.mb	X:\ISOs\missing\amd64missing\
copy /y /b .\winword.doc	X:\ISOs\missing\amd64missing\
copy /y /b .\winword2.doc	X:\ISOs\missing\amd64missing\
copy /y /b .\winzm.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\winzm.ime	X:\ISOs\missing\amd64missing\
copy /y /b .\winzm.mb	X:\ISOs\missing\amd64missing\
copy /y /b .\wmaccess.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\wmfsdk.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\wmic.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wmifltrw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wmp.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\wmplay.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wmpocm.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\wmpshell.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wordpad.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wordpad.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\wow64.cat	X:\ISOs\missing\amd64missing\
copy /y /b .\wow64mib.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wowlang.cat	X:\ISOs\missing\amd64missing\
copy /y /b .\wpa.dbl	X:\ISOs\missing\amd64missing\
copy /y /b .\wpaback.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\wpabaln.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\wpabtm.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\wpaflag.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\wpakey.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\wpatop.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\wpaw.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wpd.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\wpd_ci.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wpdmtp.inf	X:\ISOs\missing\amd64missing\
copy /y /b .\write.wpc	X:\ISOs\missing\amd64missing\
copy /y /b .\ws03res.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ws2_32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ws2help.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\ws2ifsl.sys	X:\ISOs\missing\amd64missing\
copy /y /b .\wscenter.mof	X:\ISOs\missing\amd64missing\
copy /y /b .\wschelp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wscntfy.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\wscript.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wscript.exe	X:\ISOs\missing\amd64missing\
copy /y /b .\wscript.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\wscsvc.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wscui.cpl	X:\ISOs\missing\amd64missing\
copy /y /b .\wsdu.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wsdueng.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wsecedit.hlp	X:\ISOs\missing\amd64missing\
copy /y /b .\wshcon.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wshcon.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wshext.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wshom.ocx	X:\ISOs\missing\amd64missing\
copy /y /b .\wshqos.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wshrm.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wsock32.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wuapi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wuau.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wuaucpl.cpl	X:\ISOs\missing\amd64missing\
copy /y /b .\wuauhelp.chm	X:\ISOs\missing\amd64missing\
copy /y /b .\wucltui.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wups.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wups2.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\wuweb.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_bdg.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_bec.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_beu.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_ecp.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_ecu.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_fcd.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_fcw.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_hlp.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_loc.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_mas.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_mcc.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_mcu.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_mpc.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_mpu.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_reg.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_ssd.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_wiz.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlp_wp.xdr	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlprov.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\xmlprovi.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\xolehlp.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\xpblkpop.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\xpinfbar.wav	X:\ISOs\missing\amd64missing\
copy /y /b .\xpob2res.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\xpsp2res.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht00d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht00w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht01d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht01w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht02d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht02w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht03d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht03w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht04d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht04w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht05d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht05w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht06d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht06w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht07d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht07w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht08d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht08w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht09d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht09w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht10d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht10w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht11d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht11w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht12d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht12w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht13d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht13w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht14d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht14w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht15d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht15w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht16d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht16w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht17d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht17w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht18d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht18w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht19d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht19w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht20d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht20w.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht21d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht21w.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht22d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht22w.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht23d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht23w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht24d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht24w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht25d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht25w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht26d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht26w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht27d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht27w.js	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht28d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht28w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht29d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht29w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht30d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht30w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht31d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht31w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht32d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht32w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht33d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht33w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht34d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht34w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht35d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht35w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht36d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht36w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht37d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht37w.css	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht38d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht38w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht39d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht39w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht40d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht40w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht41d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht41w.htm	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht42d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht43d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht44d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht45d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht46d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht47d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht48d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht49d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht50d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht51d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht52d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht53d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht54d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht55d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht56d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht57d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht58d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht59d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht60d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht61d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht62d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht63d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht64d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht65d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht66d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht67d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht68d.gif	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht69d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht70d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht71d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht72d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht73d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht74d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht75d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht76d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht77d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht78d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht79d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht80d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\xptht81d.jpg	X:\ISOs\missing\amd64missing\
copy /y /b .\zipfldr.dll	X:\ISOs\missing\amd64missing\
copy /y /b .\zoneoc.dll	X:\ISOs\missing\amd64missing\
copy /y /b 